# Generated by Django 5.1.4 on 2024-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_scopes_alter_tag_articles_delete_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopes',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
