# Generated by Django 5.1.4 on 2024-12-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scopes_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='topic',
            new_name='name',
        ),
    ]
